### ISSUE TITLE
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

### ISSUE THREAD

**Issue by sainisanjay** [GuangmingZhu/Conv3D_CLSTM#9]
Dear @GuangmingZhu , I have modified the ...tensorlayer/layers/recurrent.py layer as per tensorlayer-rnnlayer.py. However, I am getting following errors, do you have any idea how to solve????

```
Traceback (most recent call last):
  File "training_skig_rgb.py", line 48, in <module>
    networks = net.c3d_clstm(x, num_classes, False, True)
  File "..../C3Dtensorflow_CLSTM/c3d_clstm.py", line 86, in c3d_clstm
    name='clstm_layer_1')
  File "..../tensor/local/lib/python2.7/site-packages/tensorlayer/decorators/deprecated_alias.py", line 24, in wrapper
    return f(*args, **kwargs)
  File "..../tensor/local/lib/python2.7/site-packages/tensorlayer/layers/recurrent.py", line 236, in __init__
    (cell_output, state) = cell(self.inputs[:, time_step, :], state)
  File "..../C3Dtensorflow_CLSTM/ConvLSTMCell.py", line 72, in __call__
    c, h = array_ops.split(3, 2, state)
  File "..../tensor/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1315, in split
    axis=axis, num_split=num_or_size_splits, value=value, name=name)
  File "..../tensor/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7793, in split
    "Split", split_dim=axis, value=value, num_split=num_split, name=name)
  File "..../tensor/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 533, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.


```

**Comment by shajie17** [comment]
@sainisanjay Did you solve it?
